first pass at task sep 025
ethereum-optimism/superchain-ops pull request #418
Opened 2024-12-17 14:36 UTC by geoknee

TODO 
- [ ] upgrade to a multi chain task when things are working for OP Sepolia

2024-12-17 15:50 UTC, geoknee commented on tasks/sep/026-holocene-system-config-upgrade-and-init-multi-chain/VALIDATION.md
> +## State Changes
This should also ideally show the `baseFeeScalar` and `blobbaseFeeScalar` changes.

2024-12-19 16:40 UTC, sebastianst commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/NestedSignFromJson.s.sol
> +    SystemConfigUpgrade[1] sysCfgUpgrades;
```suggestion
    SystemConfigUpgrade[] sysCfgUpgrades;
```

2024-12-19 16:40 UTC, sebastianst commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/NestedSignFromJson.s.sol
> +            sysCfgUpgrades[i] = new SystemConfigUpgrade(l1ChainName, l2ChainNames[i], release);
```suggestion
            sysCfgUpgrades.push(new SystemConfigUpgrade(l1ChainName, l2ChainNames[i], release));
```

2025-01-03 16:30 UTC, geoknee commented on script/verification/Verification.s.sol
> +        // TODO handle chains which are missing these values:
Flagging this TODO

2025-01-03 16:31 UTC, geoknee commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/OVERVIEW.md
> +The batch will be executed on chain ID `11155111`, and contains `3` transactions.
TODO: There are more transactions now since we made it a multi chain task.

2025-01-03 18:27 UTC, geoknee commented on script/verification/Verification.s.sol
> +        // TODO handle chains which are missing these values:
[3741e88](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/3741e88f01384df8b2ea69d3533cf25c0abffd2f)

2025-01-04 00:01 UTC, geoknee commented on tasks/sep/026-holocene-system-config-upgrade-and-init-multi-chain/VALIDATION.md
> +## State Changes
[c93994a](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/c93994a645d12455919360f83ded1b9b1fdf3910)

2025-01-04 00:01 UTC, geoknee commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/OVERVIEW.md
> +The batch will be executed on chain ID `11155111`, and contains `3` transactions.
[0916f19](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/0916f198c3cfab43c3ba83d1f73b528fb7895e77)

2025-01-06 18:43 UTC, geoknee commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/NestedSignFromJson.s.sol
> +            sysCfgUpgrades.push(new SystemConfigUpgradeEcotoneScalars(l1ChainName, l2ChainNames[i], release));
Here we deploy a new `SystemConfigUpgradeEcotoneScalars` per chain, which each contains its own bindings to the appropriate SuperchainRegistry data.

2025-01-06 18:44 UTC, geoknee commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/NestedSignFromJson.s.sol
> +            sysCfgUpgrades.push(new SystemConfigUpgradeEcotoneScalars(l1ChainName, l2ChainNames[i], release));
Each instance caches some information when it is created, and this cached data is used to verify that (aside from the Ecotone scalars) no data changed in the `SystemConfig` after the task is executed.

2025-01-06 22:12 UTC, mds1 commented on script/verification/SystemConfigUpgrade.s.sol
> +        SuperchainRegistry(l1ChainName, l2ChainName, release)
Since `l1ChainName` and `l2ChainName` are storage variable names in the `SuperchainRegistry` contract, using them as argument names in the constructors shadows those variable names
```suggestion
    constructor(string memory _l1ChainName, string memory _l2ChainName, string memory _release)
        SuperchainRegistry(_l1ChainName, _l1ChainName, _release)
```

2025-01-06 22:13 UTC, mds1 commented on script/verification/SystemConfigUpgrade.s.sol
> +contract SystemConfigUpgrade is SuperchainRegistry {
Can you add comments explaining what this contract is supposed to do and when it should be used? Would be good to have explanatory comments in `Verification.s.sol` as well

2025-01-06 22:15 UTC, mds1 commented on script/verification/SystemConfigUpgrade.s.sol
> +import {NestedMultisigBuilder} from "@base-contracts/script/universal/NestedMultisigBuilder.sol";
removing unused imports
```suggestion
import {LibString} from "solady/utils/LibString.sol";
import {SuperchainRegistry} from "script/verification/Verification.s.sol";
import {ISystemConfig} from "./ISystemConfig.sol";
import {IResourceMetering} from "./IResourceMetering.sol";
```

2025-01-06 22:21 UTC, mds1 commented on script/verification/SystemConfigUpgradeEcotoneScalars.s.sol
> +        SystemConfigUpgrade(l1ChainName, l2ChainName, release)
same comment on variable shadowing
```suggestion
    constructor(string memory _l1ChainName, string memory _l2ChainName, string memory _release)
        SystemConfigUpgrade(_l1ChainName, _l2ChainName, _release)
```

2025-01-06 22:21 UTC, mds1 commented on script/verification/SystemConfigUpgradeEcotoneScalars.s.sol
> +import {NestedMultisigBuilder} from "@base-contracts/script/universal/NestedMultisigBuilder.sol";
removing unused imports

2025-01-06 22:21 UTC, mds1 commented on script/verification/SystemConfigUpgradeEcotoneScalars.s.sol
> +contract SystemConfigUpgradeEcotoneScalars is SystemConfigUpgrade {
Same comment about adding explanatory code comments

2025-01-06 22:22 UTC, mds1 commented on script/verification/SystemConfigUpgradeEcotoneScalars.s.sol
> +            (uint256(0x01) << 248) | (uint256(sysCfg.blobbasefeeScalar()) << 32) | sysCfg.basefeeScalar();
Is this only needed temporarily since we are upgrading the SystemConfig to a version that no longer needs encoding?

2025-01-06 22:25 UTC, mds1 commented on script/verification/SystemConfigUpgradeEcotoneScalars.s.sol
> +        ) {
Why is this behind an `if` block? A code comment for what this method is testing would be helpful for people not familiar with this encoding

2025-01-06 22:29 UTC, mds1 commented on script/verification/Verification.s.sol
> +    }
We can delete this, update our forge-std version to the latest release, and instead use: https://github.com/foundry-rs/forge-std/blob/b5a86914561f38735ef1fc357685de3e7c92dc48/src/StdToml.sol#L148

You can either use it like this:
```solidity
stdToml.readAddressOr(toml, "$.addresses.AnchorStateRegistryProxy", address(0));
```
or like this, similar to LibString
```solidity
using StdToml for string;

// --- snip ---

toml.readAddressOr("$.addresses.AnchorStateRegistryProxy", address(0));
```

2025-01-06 22:30 UTC, mds1 commented on tasks/sep/020-holocene-system-config-upgrade-multi-chain/README.md
> +> ⚠️ **Warning:** This task is incorrect and is superceded by [Task 027](../027-holocene-system-config-upgrade-and-init-multi-chain/)
nit (according to my spellchecker extension, I also thought your spelling was correct)
```suggestion
> ⚠️ **Warning:** This task is incorrect and is superseded by [Task 027](../027-holocene-system-config-upgrade-and-init-multi-chain/)
```

2025-01-06 22:32 UTC, mds1 commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/NestedSignFromJson.s.sol
> +    string constant release = "v1.8.0-rc.4";
The gov proposal has passed so we don't need to use the RC anymore and should be using the finalized release, which is what we want for mainnet also
```suggestion
    string constant release = "v1.8.0";
```

2025-01-06 22:36 UTC, mds1 commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/OVERVIEW.md
I'd suggest deleting this file since we don't need it, just one less thing to review

2025-01-06 22:37 UTC, mds1 commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/README.md
> +Status: DRAFT, NOT READY TO SIGN
what do we need for this to become ready to sign?
```suggestion
Status: DRAFT, NOT READY TO SIGN
```

2025-01-06 22:39 UTC, mds1 commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/README.md
> +[v1.8.0-rc.4](https://github.com/ethereum-optimism/optimism/tree/v1.8.0-rc.4) release.
we should just use 1.8.0 now that it's passed
```suggestion
This upgrades the `SystemConfig` in the
[v1.8.0](https://github.com/ethereum-optimism/optimism/tree/v1.8.0) release.
```

2025-01-06 22:41 UTC, mds1 commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/README.md
> +- `SystemConfig` - `0x33b83E4C305c908B2Fc181dDa36e230213058d7d`
Any messages you can link to so I can verify this address?

2025-01-06 22:42 UTC, mds1 commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/README.md
> +When simulating, ensure the logs say `Using script /your/path/to/superchain-ops/tasks/<path>/NestedSignFromJson.s.sol`.
```suggestion
When simulating, ensure the logs say `Using script /your/path/to/superchain-ops/tasks/027-holocene-system-config-upgrade-and-init-multi-chain/NestedSignFromJson.s.sol`.
```

2025-01-06 22:42 UTC, mds1 commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/VALIDATION.md
> +# Validation
I have not yet validated this file or run the simulation

2025-01-07 11:23 UTC, geoknee commented on script/verification/SystemConfigUpgrade.s.sol
> +        SuperchainRegistry(l1ChainName, l2ChainName, release)
[5098753](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/5098753ad37ac09680f6978ec39371d9a961e403)

2025-01-07 11:37 UTC, geoknee commented on script/verification/SystemConfigUpgrade.s.sol
> +contract SystemConfigUpgrade is SuperchainRegistry {
[ab72af4](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/ab72af4dca4dbdbcdc782b32a41a21bbd7275eb8)

2025-01-07 11:37 UTC, geoknee commented on script/verification/SystemConfigUpgrade.s.sol
> +import {NestedMultisigBuilder} from "@base-contracts/script/universal/NestedMultisigBuilder.sol";
[ab72af4](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/ab72af4dca4dbdbcdc782b32a41a21bbd7275eb8)

2025-01-07 11:38 UTC, geoknee commented on script/verification/SystemConfigUpgradeEcotoneScalars.s.sol
> +        SystemConfigUpgrade(l1ChainName, l2ChainName, release)
[ddad3df](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/ddad3df754d97266685eda3b6f0eac63fcc37ee1)

2025-01-07 11:39 UTC, geoknee commented on script/verification/SystemConfigUpgradeEcotoneScalars.s.sol
> +import {NestedMultisigBuilder} from "@base-contracts/script/universal/NestedMultisigBuilder.sol";
[ab72af4](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/ab72af4dca4dbdbcdc782b32a41a21bbd7275eb8)

2025-01-07 11:39 UTC, geoknee commented on script/verification/SystemConfigUpgradeEcotoneScalars.s.sol
> +contract SystemConfigUpgradeEcotoneScalars is SystemConfigUpgrade {
[ab72af4](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/ab72af4dca4dbdbcdc782b32a41a21bbd7275eb8)

2025-01-07 13:29 UTC, geoknee commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/NestedSignFromJson.s.sol
> +            sysCfgUpgrades.push(new SystemConfigUpgradeEcotoneScalars(l1ChainName, l2ChainNames[i], release));
Added these explanations into the source code itself, as comments.

2025-01-07 13:47 UTC, geoknee commented on script/verification/Verification.s.sol
> +    }
Nice. [8a770be](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/8a770be124b6d7de8ee085e31dc7eaac0fa43ba3)

2025-01-07 13:52 UTC, geoknee commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/README.md
> +Status: DRAFT, NOT READY TO SIGN
I updated it now, there are no blockers other than review of this PR.

2025-01-07 14:01 UTC, geoknee commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/README.md
> +[v1.8.0-rc.4](https://github.com/ethereum-optimism/optimism/tree/v1.8.0-rc.4) release.
I agree that passing governance process is a prompt for us finalizing the release. We have some options on the ordering of next steps however: 
1. We can (should) make the final tag now in any case.
2. We can update the superchain registry TOML files with the finalized tag, either 
    a. by adding a new release to `standard-versions-mainnet.toml` and keeping the existing `v1.8.0-rc.4` entry. We would then want to go back and remove the latter when all tasks referencing it have been executed.
    b. by modifying the existing release but waiting to do that until all tasks including this one are executed
    c. by modifying the existing release and modifying any existing tasks that reference it.
    
Curious what you think makes the most sense? I'd prefer if we can settle on a flow which is as clear and consistent as possible given we will go through this on each and every hard fork / upgrade. I'm inclined towards option b.

2025-01-07 15:21 UTC, geoknee commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/OVERVIEW.md
[8a770be](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/8a770be124b6d7de8ee085e31dc7eaac0fa43ba3)

2025-01-07 16:40 UTC, geoknee commented on script/verification/SystemConfigUpgradeEcotoneScalars.s.sol
> +            super.checkSystemConfigUpgrade();
[58bc135](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/58bc135aea37965cb7c3a61baafe836ae4a3b86b) and [5253651](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/5253651eb9ce4c764cbc22e6cd32c0c3a26d01eb)

2025-01-07 16:51 UTC, geoknee commented on script/verification/SystemConfigUpgradeEcotoneScalars.s.sol
> +        ) {
Tidied that up here [5253651](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/5253651eb9ce4c764cbc22e6cd32c0c3a26d01eb) PTAL hopefully it is clear now.

2025-01-07 17:01 UTC, geoknee commented on script/verification/SystemConfigUpgrade.s.sol
> +// - basedeeScalar
```suggestion
// - basefeeScalar
```

2025-01-07 17:06 UTC, geoknee commented on script/verification/SystemConfigUpgradeEcotoneScalars.s.sol
> +            (uint256(0x01) << 248) | (uint256(sysCfg.blobbasefeeScalar()) << 32) | sysCfg.basefeeScalar();
The `sysCfg.blobbasefeeScalar()` and `sysCfg.basefeeScalar()` getters read from dedicated storage slots. When we did the upgrade incorrectly previously, these storage slots were not updated causing the getters to return `0`. Now, we are checking they return values consistent with what you get if you call `sysCfg.scalar()` and decode them by hand. 

Essentially we implicitly construct the expected values for the two new getters by reencoding what we get after the upgrade and checking it matches the previous `scalar` value.

I could try redesigning this so it is more explicit, and decode the expected values from the previous.scalar and compare the new getter's results with those?

2025-01-08 10:12 UTC, geoknee commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/README.md
> +- `SystemConfig` - `0x33b83E4C305c908B2Fc181dDa36e230213058d7d`
See also https://github.com/ethereum-optimism/optimism/issues/13009

2025-01-08 22:38 UTC, geoknee commented on script/verification/SystemConfigUpgrade.s.sol
> +// - blobbasefeeScalar
On reflection, this base contract seems less and less useful as a reusable component. So I might look to combine it with `SystemConfigUpgradeEcotoneScalars` and rename that to `SystemConfigUpgradeHolocene`.

2025-01-08 22:38 UTC, geoknee commented on script/verification/SystemConfigUpgrade.s.sol
> +// - blobbasefeeScalar
(It will still be reusable across L1 and L2 chain contexts, just not across upgrades to future versions).

2025-01-09 13:08 UTC, geoknee commented on script/verification/SystemConfigUpgrade.s.sol
> +// - blobbasefeeScalar
Done

2025-01-09 17:21 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +    // The constructor caches some information from the SCR and from the existing SystemConfig contract
```suggestion
    // The constructor caches some information from the Superchain Registry and from the existing SystemConfig contract
```

2025-01-09 17:33 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +    function checkScalar() internal view {
```suggestion
    // Checks scalar, basefeeScalar, blobbasefeeScalar are set consistently.
    // The upgrade will modify (via the initialize() method) the storage slots for scalar (pre-existing), basefeeScalar (new) and blobbasefeeScalar (new). 
    // checkScalar() reads the variables from the new slot and reencodes them into reecondedScalar (which is a packed version). It then checks that this is equal to the scalar value before the upgrade (previousScalar). In this way, we indirectly prove that the new slots were set correctly (in a way consistent with existing data in the SystemConfig contract). 
    function checkScalar() internal view {
```

2025-01-09 17:36 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +            uint8(previousScalar >> 248) == 1
Something like this can be clearer:

```solidity
scalarVersion =uint8(previousScalar >> 248);
if  scalarVersion == 1 {
```

2025-01-09 17:43 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +            require(reencodedScalar << 8 == previousScalar << 8, "scalar-104 scalar mismatch");
Two comments on this: 
1. It's not very clear, if we define a variable or at least put in the revert reason "`baseFeeScalar`" that would help a lot
2. The bit shift looks wrong, we probably want  `<< 32` instead of `<< 8`

2025-01-09 18:54 UTC, Ethnical commented on lib/forge-std
- [ ] Make sure this is not causing issue during simulation + broadcast (cf: This issue we had on the previous upgrades: https://github.com/foundry-rs/foundry/issues/9648)

2025-01-09 20:27 UTC, Ethnical commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +            require(reencodedScalar << 8 == previousScalar << 8, "scalar-104 scalar mismatch");
Looks like this is not working indeed, i tried with the mask `0xfffff` and this seems to have a more reasonable value @geoknee: 
![14aa2bca398d7e38779daed1c1b54d44fb9d852fb8378e0b4641ebcf9c47b124](https://github.com/user-attachments/assets/959348b9-a03d-4a7e-9eaf-2bafb8daf00c)

2025-01-09 20:45 UTC, Ethnical commented on script/verification/IResourceMetering.sol
> +    function __constructor__() external;
NIT: curious to know if this is required?

2025-01-09 20:55 UTC, Ethnical commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/VALIDATION.md
> +  **After**: `0xx00000000000000000000000000000000000d273000001db00000000003938700`
There is a typo 
```suggestion
  **After**: `0x00000000000000000000000000000000000d273000001db00000000003938700`
```

2025-01-09 21:04 UTC, Ethnical commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/VALIDATION.md
> +  **Meaning**: Updates the `basefeeScalar` and `blobbasefeeScalar` storage variables to `7600` and `86200` respectively. These share a slot with the `gasLimit` which remans at `60000000`
@geoknee there is an error here the state is updating with `862000`. 
We should make sure this is desired and this is a simple typo here: 

```
`86200` respectively.
```

2025-01-09 21:24 UTC, Ethnical commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/VALIDATION.md
> +- **Key**: See above.
imo "see above" is not clear enough here. 
we should faciliate the access to the information to make sure signers can make sure they can highlight any difference directly. 
```suggestion
- **Key**: In the [`approvedHashes` section line 18](/blob/main/tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/VALIDATION.md#L18)
```

2025-01-09 21:26 UTC, Ethnical reviewed
Super work with the framework for the SuperConfig upgrade! 🔥

The validation "storage" **matched** the simulation. But some value into the validation file need to be revisited.  
There is few things to complete before merge but would be fast!
 
![CleanShot 2025-01-09 at 22 26 06@2x](https://github.com/user-attachments/assets/99152672-4663-46e8-8fac-8e2f015497a3)

2025-01-10 09:47 UTC, geoknee commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/input.json
> +        "name": "ProxyAdmin.upgrade(SystemConfigProxy, StorageSetter)",
It is uncertain whether this step is necessary after all.

2025-01-10 10:54 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +            require(reencodedScalar << 8 == previousScalar << 8, "scalar-104 scalar mismatch");
Fixed this here. In fact what I was trying to do was compare the scalars _without_ the scalar version (first byte). [556d1d5](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/556d1d51bc7b73b13cc9aeda26cb54c042f589ad)

2025-01-10 10:55 UTC, geoknee commented on script/verification/IResourceMetering.sol
> +    function __constructor__() external;
[cd7ec86](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/cd7ec86dcb90083996058af5ca57e1233c4374cf)

2025-01-10 11:10 UTC, geoknee commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/VALIDATION.md
> +  **Meaning**: Updates the `basefeeScalar` and `blobbasefeeScalar` storage variables to `7600` and `86200` respectively. These share a slot with the `gasLimit` which remans at `60000000`
Yes you are right this is a typo. I decoded it again by hand and have corrected the doc.

2025-01-10 11:10 UTC, geoknee commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/VALIDATION.md
> +  **Meaning**: Updates the `basefeeScalar` and `blobbasefeeScalar` storage variables to `68400` and `0` respectively. These share a slot with the `gasLimit` which remans at `30000000`
Yes you are right this is a typo. I decoded it again by hand and have corrected the doc.

2025-01-10 12:04 UTC, Ethnical submitted a review, later dismissed
LGTM! rechecked the tasks validation + simulation make sense to me!

2025-01-10 12:07 UTC, Ethnical commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +            require(reencodedScalar << 8 == previousScalar << 8, "scalar-104 scalar mismatch");
Hmm, 
Just to make sure, you want to compare the if the first byte (`0x0`) are correctly incremented to (`0x1`) when the value `scalarVersion` is `0` right (if yes for me it works as expected). 
![CleanShot 2025-01-10 at 13 05 23@2x](https://github.com/user-attachments/assets/0912c0e9-1cf1-470d-b3f5-e032e938c91e)

2025-01-10 14:46 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +            require(reencodedScalar << 8 == previousScalar << 8, "scalar-104 scalar mismatch");
Yes that's right.

2025-01-10 15:50 UTC, sebastianst reviewed
Part 1

2025-01-10 15:50 UTC, sebastianst commented on lib/forge-std
is the forge-std upgrade intended?

2025-01-10 15:50 UTC, sebastianst commented on script/verification/Verification.s.sol
> +import {console2 as console} from "forge-std/console2.sol";
this is already happening on line 4?

2025-01-10 15:50 UTC, sebastianst commented on script/verification/Verification.s.sol
> +contract SuperchainRegistry is ScriptBase {
what's the difference? why don't we want or need this for all other script contacts?

2025-01-10 15:50 UTC, sebastianst commented on script/verification/Verification.s.sol
> +        chainConfig.unsafeBlockSigner = stdToml.readAddressOr(toml, "$.addresses.UnsafeBlockSigner", address(0));
I'd still put this line back to where it was, so it's grouped with the other chainConfig setters as before.

2025-01-10 15:50 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +interface ISystemConfig {
Isn't the interface available from the imported `@eth-optimism-bedrock` package at `@eth-optimism-bedrock/src/L1/interfaces/ISystemConfig` or so? Edit: doesn't seem so. But it would be in a more recent commit of the monorepo. E.g. https://github.com/ethereum-optimism/optimism/blob/proposal/op-contracts/v1.8.0/packages/contracts-bedrock/src/L1/interfaces/ISystemConfig.sol has it. On `develop` the `interfaces` got moved into a directory tree next to the `src` tree, if we want to use a recent monorepo commit instead...

2025-01-10 15:50 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +            targetDGF = sysCfg.disputeGameFactory();
could merge them
```suggestion
        if (sysCfg.version().eq("2.3.0") || sysCfg.version().eq("2.2.0")) {
            // Supported initial version
            targetDGF = sysCfg.disputeGameFactory();
```

2025-01-10 15:50 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +        SuperchainRegistry(_l1ChainName, _l2ChainName, _release)
You can make the contract `abstract` and then don't need to pass down initialization of the `SuperchainRegistry` contract. This is more modular. See my recent fp upgrade tasks, where the actual check script instantiation directly calls the `SuperchainRegistry` constructor.

```suggestion
    constructor() # and make contract abstract
```

2025-01-10 15:50 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +            keccak256(abi.encode(getSysCfgVersion())) == keccak256(abi.encode(targetVersion)),
```suggestion
            getSysCfgVersion().eq(targetVersion),
```

2025-01-10 15:50 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +        return sysCfg.version();
if you change to use an imported `ISystemConfig`, you can get the `version()` function with interface `ISemver`.

2025-01-10 15:50 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +    function checkSystemConfigUpgrade() public view {
Do you check for parity of the `resourceConfig`, or is this not necessary? If not, and you can't import the `ISystemConfig` interface from the monorepo, you could trim down the interface you define below in the file to only those functions you need, and also remove the `IResourceMetering` and its contained struct.

2025-01-10 15:50 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +}
I think you could also just define the struct directly
```suggestion
struct ResourceConfig {
    uint32 maxResourceLimit;
    uint8 elasticityMultiplier;
    uint8 baseFeeMaxChangeDenominator;
    uint32 minimumBaseFee;
    uint32 systemTxMaxGas;
    uint128 maximumBaseFee;
}
```

2025-01-10 15:50 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +    }
A better pattern with the verification framework is to make the contract also a `VerificationBase` and then here do
```suggestion
    function _getCodeExceptions() internal {
        if (block.chainid != 1) addCodeException(previous.owner);
        addCodeException(address(uint160(uint256(previous.batcherHash))));
        addCodeException(previous.unsafeBlockSigner);
        addCodeException(previous.batchInbox);
    }
```
then call `_getCodeExceptions()` inside the `constructor`, and in the actual check script instance, you do
```solidity
    function getAllowedStorageAccess() internal view override returns (address[] memory) {
        return allowedStorageAccess;
    }

    function getCodeExceptions() internal view override returns (address[] memory) {
        return codeExceptions;
    }
```
see for example the check script for task eth/022.

2025-01-10 15:54 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +        SuperchainRegistry(_l1ChainName, _l2ChainName, _release)
Ahh I see that you need to make multiple instances and don't inherit this contract directly... ok then it makes sense.

2025-01-10 15:56 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +    }
OK I realize you need to collect all those code exceptions from multiple instances. Still you could inherit the `VerificationBase` contract and then do something like
```suggestion
    // call this from main script
    function getCodeExceptions() public view returns (address[] memory exceptions) {
        return codeExceptions
    }
    
    //  call this from the constructor
    function _addCodeExceptions() internal {
        if (block.chainid != 1) addCodeException(previous.owner);
        addCodeException(address(uint160(uint256(previous.batcherHash))));
        addCodeException(previous.unsafeBlockSigner);
        addCodeException(previous.batchInbox);
    }
```

2025-01-10 16:04 UTC, geoknee commented on lib/forge-std
Yes. It pulls in `stdToml.readAddressOr()` which lets us handle chains which have missing data in the superchain registry.

2025-01-10 16:05 UTC, geoknee commented on script/verification/Verification.s.sol
> +contract SuperchainRegistry is ScriptBase {
I think I may be able to revert this. I had it previously because it exposed `external` TOML utilities which I could wrap with a try/catch.

2025-01-10 16:07 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +        require(keccak256(abi.encode(getBaseSysCfgVars())) == keccak256(abi.encode(previous)), "system-config-100");
```suggestion
        require(getBaseSysCfgVars().eq(previous), "system-config-100");
```

2025-01-10 16:08 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +interface ISystemConfig {
I actually think I don't want to float this dependency. This task is for a very specific SystemConfig interface so I'm pretty happy with hardcoding the interface here.

2025-01-10 16:10 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +    function checkSystemConfigUpgrade() public view {
I do check for parity for `resourceConfig`.

2025-01-10 16:11 UTC, sebastianst commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/NestedSignFromJson.s.sol
> +            console.log("Running post-deploy assertions for chain", l2ChainNames[i], "-", l1ChainName);
nit, I think the convention is the other way round
```suggestion
            console.log("Running post-deploy assertions for chain", l1ChainName, "-", l2ChainNames[i]);
```

2025-01-10 16:14 UTC, sebastianst commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/VALIDATION.md
> +* **Key**: `0x0000000000000000000000000000000000000000000000000000000000000068`
it may make sense to link to the storage layout so that the keys can be verified.

2025-01-10 16:15 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +    }
I'm not sure this will work for my multi chain task though?

2025-01-10 16:16 UTC, sebastianst commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/VALIDATION.md
> +* **Meaning**: Updates the `basefeeScalar` and `blobbasefeeScalar` storage variables to `7600` and `862000` respectively. These share a slot with the `gasLimit` which remains at `60000000`
it would help to say that `cast th 60000000` equals `0x3938700`. same for other int-hex comparisons

2025-01-10 16:20 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +}
Perhaps, but then I need to change a bunch of references and this moves more towards a completely hand rolled interface for the SystemConfig. I like it better like this where we have a snapshot of how the interface actually looks.

2025-01-10 16:43 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +        require(keccak256(abi.encode(getBaseSysCfgVars())) == keccak256(abi.encode(previous)), "system-config-100");
I don't think this one will work because I'm not ` using LibString for BaseSysCfgVars` and I don't think I can either.

2025-01-10 16:53 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +        require(keccak256(abi.encode(getBaseSysCfgVars())) == keccak256(abi.encode(previous)), "system-config-100");
ah lol, I realize this is not a string comparison, sorry!

2025-01-10 16:53 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +interface ISystemConfig {
OK makes sense.

2025-01-10 16:57 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +    }
My proposal still gives you that. It just has two advantages
1. you use the `VerificationBase` to give you `addCodeException` to manage the array
2. if you use this contract in a single-verification (not multi-instance like this one), it's automatically compatible with that pattern.

Note that my proposal gives you the exact same `function getCodeExceptions() public view returns (address[] memory exceptions)` so same api.

2025-01-10 16:59 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +    function checkSystemConfigUpgrade() public view {
sorry yes, by hashing the whole thing 👑

2025-01-10 17:00 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +        return sysCfg.version();
I see you want to retain the explicit interface.

2025-01-10 17:01 UTC, sebastianst commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/NestedSignFromJson.s.sol
> +            console.log("Running post-deploy assertions for chain", l2ChainNames[i], "-", l1ChainName);
sorry, this is wrong, your way is correct 🙈

2025-01-10 17:13 UTC, geoknee commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/VALIDATION.md
> +* **Key**: `0x0000000000000000000000000000000000000000000000000000000000000068`
[1e1fc2b](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/1e1fc2b128be4404cd8245e3075ccaa61700cdaf)

2025-01-10 17:13 UTC, geoknee commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/VALIDATION.md
> +* **Meaning**: Updates the `basefeeScalar` and `blobbasefeeScalar` storage variables to `7600` and `862000` respectively. These share a slot with the `gasLimit` which remains at `60000000`
[3eec9d8](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/3eec9d8bfbdb740f8e7f5f5c3c0fd48e477d0e60)

2025-01-10 17:13 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +            LibString.toString(reencodedScalar)
[c904f92](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/c904f925609bcfb52c7d453b71eaf54fa9c86c54)

2025-01-10 17:17 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +            targetDGF = sysCfg.disputeGameFactory();
[31ab749](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/31ab749a1b08412a1bb4cc5b5083d54b4e30f368)

2025-01-10 17:20 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +            require(reencodedScalar == previousScalar + (uint256(0x01) << 248), "scalar-104 scalar mismatch");
We do not guarantee that. This would be to cover an invalid scalar encoding, correct? I'm assuming the scalar was encoded correctly. Do you think extra checks are warranted to cover encodings which violate the spec?

2025-01-10 17:24 UTC, geoknee commented on script/verification/Verification.s.sol
> +import {console2 as console} from "forge-std/console2.sol";
Good catch, removed.

2025-01-10 17:24 UTC, geoknee commented on script/verification/Verification.s.sol
> +contract SuperchainRegistry is ScriptBase {
I reverted this change in the end.

2025-01-10 18:09 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +    }
I see, took a crack here [acd812e](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/acd812e94dcacc0638d05501af8788fa759d657d)

2025-01-10 18:12 UTC, geoknee commented on script/verification/Verification.s.sol
> +        chainConfig.unsafeBlockSigner = stdToml.readAddressOr(toml, "$.addresses.UnsafeBlockSigner", address(0));
[17bff2d](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/17bff2d0b9a2931594f6084d6284ebe88aeaa947)

2025-01-13 11:41 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +            require(reencodedScalar == previousScalar + (uint256(0x01) << 248), "scalar-104 scalar mismatch");
It would force us to take a closer look at any chain that somehow managed to set an invalid scalar. It could also be a pre-check (called from the ctor of the check contract).

2025-01-13 11:42 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +    }
yes thanks, that what I meant :)

2025-01-13 11:45 UTC, sebastianst commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +    function _getCodeExceptions() internal {
nit, this is now an _adder_ not a _getter_.
```suggestion
    function _addCodeExceptions() internal {
```

2025-01-13 11:45 UTC, sebastianst commented on lib/forge-std
ah nice

2025-01-13 12:02 UTC, sebastianst commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/README.md
> +When simulating, ensure the logs say `Using script /your/path/to/superchain-ops/tasks/027-holocene-system-config-upgrade-and-init-multi-chain/NestedSignFromJson.s.sol`.
```suggestion
When simulating, ensure the logs say `Using script /your/path/to/superchain-ops/tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/NestedSignFromJson.s.sol`.
```
you fix this in the [mainnet pr](https://github.com/ethereum-optimism/superchain-ops/pull/454/files#diff-6e1818466a6f803978bd56a0a754e9b9de17381edc235a5f7f1a08f8f012a484)

2025-01-13 12:04 UTC, sebastianst commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/NestedSignFromJson.s.sol
> +            }
We could add the array adder to the `VerificationBase`, then we could just do
```suggestion
            addCodeExceptions(sysCfgUpgrades[i].getCodeExceptions());
```
here and in following tasks.

2025-01-13 12:24 UTC, geoknee commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/NestedSignFromJson.s.sol
> +            }
[540baec](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/540baec4113f4bed0358a24912ba6eb18d5050df)

2025-01-13 12:51 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +    function _getCodeExceptions() internal {
[a99ddbf](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/a99ddbfdc6c3b0c8a5522db44001a9d3be8473c6)

2025-01-13 12:51 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +            require(reencodedScalar == previousScalar + (uint256(0x01) << 248), "scalar-104 scalar mismatch");
[7bb795b](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/7bb795b6aab31b87178d37958f86c40fc3b44cce)

2025-01-13 13:53 UTC, sebastianst approved these changes

2025-01-13 14:19 UTC, Ethnical commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +            // Sanity check the scalar "padding" is zero for legacy encodings (see spec)
Maybe also add the link to the specs for the legacy encoding here?

2025-01-13 14:30 UTC, Ethnical commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/VALIDATION.md
> +* **After**: `0x0000000000000000000000000000000000000000000000000000000000000010`
Invalid state validation here has been incremented. 
Need to recheck why and update the correct nonce expected.

2025-01-13 14:31 UTC, Ethnical requested changes
Validation state is now incorrect with the nonce.

2025-01-13 14:43 UTC, geoknee commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/VALIDATION.md
> +* **After**: `0x0000000000000000000000000000000000000000000000000000000000000010`
[85bca50](https://github.com/ethereum-optimism/superchain-ops/pull/418/commits/85bca50362715920d34ac96536de114b590f5fa9)

2025-01-13 14:44 UTC, geoknee commented on script/verification/HoloceneSystemConfigUpgrade.s.sol
> +            // Sanity check the scalar "padding" is zero for legacy encodings (see spec)
It is already linked on L147 just above.

2025-01-13 15:27 UTC, Ethnical approved these changes

2025-01-13 15:32 UTC, geoknee commented on tasks/sep/027-holocene-system-config-upgrade-and-init-multi-chain/input.json
> +        "name": "ProxyAdmin.upgrade(SystemConfigProxy, StorageSetter)",
We won't do this step.

2025-01-13 15:39 UTC, merged